### ISSUE TITLE
Add the ability to set group as open

### ISSUE THREAD

**Issue by darkkatarsis** [thomasloven/lovelace-fold-entity-row#60]
It's possible to add the ability to set group as open when one of the children is on? It would be great

**Comment by genem2** [comment]
Exactly what I was pursuing, which led me here. I was attempting to have a fold OPEN if the state was not the norm. Example: for something like a group of lights, if any of the lights are on, expand the row, otherwise not. For the reverse logic: if a folded group of automations had any Off, expand the row. So, maybe it's just that if the state of items in the fold are not all the same state, Open by default.

Maybe just having open supporting templates could do it.
Thanks

**Comment by Digl** [comment]
Any news on how to achieve this?

**Comment by jazzyisj** [comment]
This item was requested a while ago and was closed without resolution.  I believe the request was misunderstood but Thomas seems like a pretty busy guy and it is a minor issue in the end so I didn't pursue it.

https://github.com/thomasloven/lovelace-fold-entity-row/issues/78

I believe the issue is that the fold entity row open: parameter requires an actual boolean and templates always return a string.

I had the same issue with another card (mini media player) and just ended up using a state switch to display an entirely different card (well, same with different options) when required.  Never did find another solution for this specific issue here.

**Comment by thomasloven** [comment]
This is not within the scope of this card.
Use config-template-card or something.
