### ISSUE TITLE
Option to swap fold-icon and switch

### ISSUE THREAD

**Issue by moejetz** [thomasloven/lovelace-fold-entity-row#65]
Hi! Nice work so far :)
I have a feature request: adding an option to swap the fold icon with the switch.
This way the switches are aligned properly with the "normal" switch entities, resulting in a clearer interface imho.

![Screenshot 2019-10-04 at 12 17 36](https://user-images.githubusercontent.com/7048586/66200471-734c1580-e6a1-11e9-9c45-9d72634b04d4.png)
![Screenshot 2019-10-04 at 12 17 36_2](https://user-images.githubusercontent.com/7048586/66200473-734c1580-e6a1-11e9-82fe-b58bbcb9fba8.png)

Thanks in advance :)

**Comment by starkillerOG** [comment]
+1 for this feature

**Comment by thomasloven** [comment]
That is not easily doable, and would be considered bad UX. The primary function of the fold entity row is to open and close the fold. Toggling the switch is a secondary function.

**Comment by starkillerOG** [comment]
@thomasloven would it then perhaps be possible to always have the arrow first and then the toggle switch (bottom picture in the first post), without the option to swap them?

I think the layout in the bottom picture looks way nicer.

**Comment by nickdos** [comment]
I don't buy the bad UX argument - if the default behaviour is to hide the child entities (it is), then the dominant action for that row would be to use the toggle "action" - otherwise you'd have to argue that the defat action of opening the "fold" is adding an extra step for the user - which is bad UX (don't make me think). So I see the user more often clicking the toggle icon than opening the fold (logically this follows - otherwise you'd leave the fold open by default). This is my use-case... I want to use toggle most of the time but occasionally I want to have fine control and then open the fold to control one of the child entities. So I expect the toggle to be where is always is - on the far right (not moved in slightly, as this visually confuses the users - UX dictates that the placement should be consistent and predictable). I'd be OK with the fold icon being next to the name but to the left of the toggle is OK as well.
