### ISSUE TITLE
Head Option IS Broken

### ISSUE THREAD

**Issue by Justahobby01** [thomasloven/lovelace-fold-entity-row#96]
https://github.com/thomasloven/lovelace-fold-entity-row/issues/95#issue-585763115

Not sure why this was closed when it wasn't resolved or documentation updated, but closing it just to close it only creates more confusion as more people update and see the error w/o a resolution.

**Comment by thomasloven** [comment]
You mean besides the fact that it describes the same error as **three** other recent issue reports?

I saw nothing in #95 describing how it was different from #91, #93 or #94. Nor do I see a single word about it in #96. Not even a description of the results from the extended debugging suggestions in #94.

**Comment by Justahobby01** [comment]
https://github.com/thomasloven/lovelace-fold-entity-row/issues/93#issue-584400862 didn't say what their issue was, only the generic  hui-cover-entity-row error. https://github.com/thomasloven/lovelace-fold-entity-row/issues/94#issue-584800511 magically started working so what are we supposed to think of that one? And https://github.com/thomasloven/lovelace-fold-entity-row/issues/91#issue-581361014 points out what I found - that things are broken and documentation doesn't reflect any changes.  I played around with my yaml until I figured out specifically which part was causing the error. 

 In #91 it appeared as though you addressed it with update 15, but I saw no change on my end, even after reboots, cache clearing, etc. However, I apologize. Had I known you would feel so much indignation I would have saved myself the effort and found a different solution.

**Comment by thomasloven** [comment]
This will not work as a one-sided effort.

I have a full time job and a family, and can't afford the time to guess your specific case when at least three other people have had (lacking any other evidence) exactly the same problem, and that has been solved by following the provided instructions.

The closing message in #91 contains a link to exactly the place where it was fixed.
Have you tried updating to the version released after that issue was closed?
I cannot control the comments on issues, thus the ones clearly stating another problem (not working with groups) should be ignored.

#93 is a clear duplicate of #91 and thus closed.

#94 describes a suspiciously similar issue, followed by a comment from me with instructions on how to solve it or - if that fails - how to get further indication on what may be wrong.
Note that those instructions were not followed - probably because the author waited it out rather than going back to follow the instructions in the bug report template.

Speaking of the bug report template (which contains instructions on what information to provide to help me help you), I see no trace of it in either of your issues, and would, reluctantly, like to point to the following part of it:

> **By putting an X in the boxes ([ ]) below, I indicate that I:**
>
> [...]
> - [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
